### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by vncastanheira** [alimg/androidmic#3]
Hey, this looks like a very interesting project.
However, I'm having some trouble running it.
First installed Python 3.8.2 and it warned me about requiring `scipy`.
Installed than and then it gave another warning requiring `sld2`.
Tried installing PySDL2 0.9.7 and now I'm getting the following error:

```
Traceback (most recent call last):
  File "C:\Users\Vinicius\AppData\Roaming\Python\Python38\site-packages\sdl2\dll.py", line 223, in <module>
    dll = DLL("SDL2", ["SDL2", "SDL2-2.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "C:\Users\Vinicius\AppData\Roaming\Python\Python38\site-packages\sdl2\dll.py", line 104, in __init__
    raise RuntimeError("could not find any library for %s (%s)" %
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\General Projects\androidmic\server\audio.py", line 6, in <module>
    from sdl2 import *
  File "C:\Users\Vinicius\AppData\Roaming\Python\Python38\site-packages\sdl2\__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "C:\Users\Vinicius\AppData\Roaming\Python\Python38\site-packages\sdl2\dll.py", line 225, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)
```

Now I'm unsure what do to. Can you help me?

**Comment by alimg** [comment]
Looks like you're trying to run this on Windows. Unfortunately this projects supports Linux only. You could technically run the script on Windows but the microphone functionality will probably not work because pulseaudio does not exist.

If you're interested to run this nevertheless, looks like you need to install pysdl2-dll package as documented on their PyPI package. 

You'll need to find a workaround for the pactl commands on Windows to make it run as microphone. If you do so, please feel free to update instructions on the README file.

Good luck!
