### ISSUE TITLE
Problem with server

### ISSUE THREAD

**Issue by santoni0** [alimg/androidmic#4]
Hello
I compiled the application and turned on the server. I don't see it working at pavucontrol. My log: 
```
Traceback (most recent call last):
 File "server.py", line 5, in <module> from audio import RawAudio 
 File "/root/androidmic/server/audio.py", line 3. in <module> from scipy.signal import resample         
 ModuleNotFoundError: No module named scipy
```
I installed scipy using apt.
How can I get it working?

**Comment by KaspAdam** [comment]
I installed scipy using apt
